# Generated by Django 2.2.7 on 2019-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20191121_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='imagefile',
            field=models.FileField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
