# Generated by Django 2.2.7 on 2019-11-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20191121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='image', max_length=500),
        ),
    ]
